---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: rhel-6.5
    driver:
      box: datapipeRHEL65
      box_url: https://s3-us-west-2.amazonaws.com/packages.dualspark.com/dev/vagrant/rhel-6.5.virtualbox.box

suites:
  - name: default
    run_list:
    attributes:
